# Generated by Django 4.1.13 on 2024-08-23 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=60, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ключевое слово')),
            ],
            options={
                'verbose_name': 'Ключевое слово',
                'verbose_name_plural': 'Ключевые слова',
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tour_id', models.AutoField(primary_key=True, serialize=False)),
                ('title_tour', models.CharField(max_length=200, verbose_name='Название лекции')),
                ('price_single', models.CharField(blank=True, max_length=200, null=True, verbose_name='Цена для одного')),
                ('price_group', models.CharField(blank=True, max_length=200, null=True, verbose_name='Цена для группы')),
                ('meet_point', models.CharField(blank=True, max_length=200, null=True, verbose_name='Точка сборки')),
                ('duration', models.CharField(blank=True, max_length=200, null=True, verbose_name='Длительность')),
                ('annotation_tour', models.TextField(verbose_name='Анонс лекции')),
                ('questions', models.TextField(verbose_name='Вы узнаете ответы')),
                ('img_tour_main', models.ImageField(blank=True, null=True, upload_to='lection/', verbose_name='Фото в шапку страницы')),
                ('img_tour_1', models.ImageField(blank=True, null=True, upload_to='lection/', verbose_name='Фото в шапку страницы')),
                ('img_tour_2', models.ImageField(blank=True, null=True, upload_to='lection/', verbose_name='Фото в шапку страницы')),
                ('img_tour_3', models.ImageField(blank=True, null=True, upload_to='lection/', verbose_name='Фото в шапку страницы')),
                ('img_tour_4', models.ImageField(blank=True, null=True, upload_to='lection/', verbose_name='Фото в шапку страницы')),
                ('img_tour_5', models.ImageField(blank=True, null=True, upload_to='lection/', verbose_name='Фото в шапку страницы')),
                ('img_tour_6', models.ImageField(blank=True, null=True, upload_to='lection/', verbose_name='Фото в шапку страницы')),
                ('img_tour_7', models.ImageField(blank=True, null=True, upload_to='lection/', verbose_name='Фото в шапку страницы')),
                ('img_tour_8', models.ImageField(blank=True, null=True, upload_to='lection/', verbose_name='Фото в шапку страницы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_categories', to='tour.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(blank=True, related_name='tours', to='tour.tag')),
            ],
            options={
                'verbose_name': 'Экскурсия',
                'verbose_name_plural': 'Экскурсии',
                'ordering': ['title_tour'],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag'], name='tour_tag_tag_3ce5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category'], name='tour_catego_categor_d7c88e_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['title_tour'], name='tour_tour_title_t_f3bb7b_idx'),
        ),
    ]
