# Generated by Django 4.1.13 on 2024-08-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='annotation_tour',
            field=models.TextField(verbose_name='Краткое описание экскурсии'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title_tour',
            field=models.CharField(max_length=200, verbose_name='Название экскурсии'),
        ),
    ]
