# Generated by Django 4.2.2 on 2023-06-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=250, verbose_name='Название статьи'),
        ),
    ]
