# Generated by Django 4.2.2 on 2023-06-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_header',
        ),
    ]
