# Generated by Django 4.2.2 on 2023-06-29 09:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_body',
            field=ckeditor.fields.RichTextField(default='А я иду, шагаю...'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_annotation',
            field=models.TextField(verbose_name='Аннотация статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_category',
            field=models.CharField(default='Пешком по городу', max_length=100),
        ),
    ]
