# Generated by Django 4.2.2 on 2023-06-29 09:47

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_article_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_body',
            field=django_quill.fields.QuillField(default='А я иду, шагаю...'),
        ),
    ]
