# Generated by Django 4.2.2 on 2023-06-29 09:49

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_body',
            field=django_quill.fields.QuillField(default='А я иду, шагаю...', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_category',
            field=models.CharField(default='Пешком по городу', max_length=100, verbose_name='Категория статьи'),
        ),
    ]
