# Generated by Django 4.2.2 on 2023-07-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_alter_article_article_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_category',
            field=models.CharField(choices=[('1', 'Пешком по городу'), ('2', 'Вокруг Петербурга'), ('3', 'Старый быт'), ('4', 'Вторая мировая'), ('5', 'Первая мировая'), ('6', 'Истории людей'), ('7', 'Истории зверей'), ('8', 'Книжные истории'), ('9', 'Искусство'), ('10', 'Секреты')], max_length=2),
        ),
    ]
