# Generated by Django 4.2.2 on 2023-07-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_article_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_category',
            field=models.CharField(choices=[('GO', 'Пешком по городу'), ('SZ', 'Вокруг Петербурга'), ('BY', 'Старый быт'), ('W2', 'Вторая мировая'), ('W1', 'Первая мировая'), ('HP', 'Истории людей'), ('HA', 'Истории зверей'), ('HB', 'Книжные истории'), ('AR', 'Искусство'), ('SE', 'Секреты')], max_length=2),
        ),
    ]
