# Generated by Django 4.2.2 on 2023-07-01 14:59

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_alter_article_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuillPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_body', django_quill.fields.QuillField(verbose_name='Текст')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_body',
        ),
    ]
