# Generated by Django 4.2.2 on 2023-07-01 16:53

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_quillpost_remove_article_article_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuillPost',
        ),
        migrations.AddField(
            model_name='article',
            name='article_body',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
