# Generated by Django 4.2.2 on 2023-06-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lection_title', models.CharField(max_length=200, verbose_name='Название лекции')),
                ('lection_annotation', models.TextField(verbose_name='Аннотация лекции')),
                ('lection_header', models.FileField(upload_to='', verbose_name='Картинка для верха страницы')),
            ],
        ),
    ]
