# Generated by Django 4.2.2 on 2023-06-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lection',
            name='lection_header',
            field=models.CharField(max_length=250, verbose_name='Картинка для верха страницы'),
        ),
    ]
