# Generated by Django 4.1.13 on 2024-08-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
