# Generated by Django 4.2.2 on 2023-06-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lection', '0002_alter_lection_lection_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lection',
            name='lection_header',
            field=models.FilePathField(max_length=250, verbose_name='Картинка для верха страницы'),
        ),
    ]
