# Generated by Django 4.1.13 on 2024-08-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lection', '0002_remove_tour_category_remove_tour_tags_delete_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lection',
            name='questions',
            field=models.TextField(default='why?', verbose_name='Вы узнаете ответы'),
        ),
    ]
