# Generated by Django 4.2.2 on 2023-06-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lection', '0003_alter_lection_lection_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lection',
            name='lection_header',
        ),
    ]
