# Generated by Django 4.1.13 on 2024-08-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lection', '0003_lection_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lection',
            old_name='img',
            new_name='img_lection',
        ),
    ]
