# Generated by Django 4.2.2 on 2023-07-02 19:15

from django.db import migrations, models
import lection.models


class Migration(migrations.Migration):

    dependencies = [
        ('lection', '0004_remove_lection_lection_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='lection',
            name='lection_pic',
            field=models.FilePathField(default='lection_hall.jpg', path=lection.models.pic_path),
        ),
    ]
