# Generated by Django 4.1.13 on 2024-09-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('press_id', models.AutoField(primary_key=True, serialize=False)),
                ('press_title', models.CharField(max_length=200, verbose_name='Название публикации')),
                ('time', models.TimeField(blank=True, null=True)),
                ('press_annotation', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('screen_1', models.ImageField(blank=True, null=True, upload_to='press/', verbose_name='Скрин 1')),
                ('screen_2', models.ImageField(blank=True, null=True, upload_to='press/', verbose_name='Скрин 2')),
                ('link', models.TextField(verbose_name='Ссылка на источник')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['press_title'],
            },
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['press_title'], name='press_publi_press_t_01bcc9_idx'),
        ),
    ]
