# Generated by Django 4.1.13 on 2024-09-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
